"""initial_6_sheets

Revision ID: 0f468f80c88a
Revises: 
Create Date: 2026-05-14 10:25:09.673104

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f468f80c88a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auto_insurance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issued_date", sa.DATE(), nullable=False),
        sa.Column("insured_name", sa.TEXT(), nullable=True),
        sa.Column("phone", sa.TEXT(), nullable=True),
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("address", sa.TEXT(), nullable=True),
        sa.Column("plate_number", sa.TEXT(), nullable=False),
        sa.Column("frame_number", sa.TEXT(), nullable=True),
        sa.Column("engine_number", sa.TEXT(), nullable=True),
        sa.Column("payload", sa.REAL(), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column("vehicle_type", sa.TEXT(), nullable=True),
        sa.Column("brand", sa.TEXT(), nullable=True),
        sa.Column("vehicle_value", sa.REAL(), nullable=True),
        sa.Column("purpose", sa.TEXT(), nullable=True),
        sa.Column("premium", sa.REAL(), nullable=True),
        sa.Column("source_email_id", sa.TEXT(), nullable=True),
        sa.Column("source_attachment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plate_number", "issued_date"),
    )
    op.create_table(
        "bhyt_bhxh_insurance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issued_date", sa.DATE(), nullable=True),
        sa.Column("insured_name", sa.TEXT(), nullable=False),
        sa.Column("insured_id_number", sa.TEXT(), nullable=True),
        sa.Column("effective_from", sa.DATE(), nullable=True),
        sa.Column("buyer_name", sa.TEXT(), nullable=True),
        sa.Column("buyer_dob", sa.DATE(), nullable=True),
        sa.Column("buyer_relation", sa.TEXT(), nullable=True),
        sa.Column("premium", sa.REAL(), nullable=True),
        sa.Column("source_email_id", sa.TEXT(), nullable=True),
        sa.Column("source_attachment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("insured_id_number", "effective_from"),
    )
    op.create_table(
        "health_insurance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issued_date", sa.DATE(), nullable=True),
        sa.Column("insured_name", sa.TEXT(), nullable=False),
        sa.Column("insured_dob", sa.DATE(), nullable=True),
        sa.Column("insured_id_number", sa.TEXT(), nullable=True),
        sa.Column("effective_from", sa.DATE(), nullable=True),
        sa.Column("outpatient", sa.REAL(), nullable=True),
        sa.Column("dental", sa.REAL(), nullable=True),
        sa.Column("maternity", sa.REAL(), nullable=True),
        sa.Column("premium", sa.REAL(), nullable=True),
        sa.Column("buyer_name", sa.TEXT(), nullable=True),
        sa.Column("buyer_dob", sa.DATE(), nullable=True),
        sa.Column("buyer_id_number", sa.TEXT(), nullable=True),
        sa.Column("buyer_relation", sa.TEXT(), nullable=True),
        sa.Column("source_email_id", sa.TEXT(), nullable=True),
        sa.Column("source_attachment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("insured_id_number", "effective_from"),
    )
    op.create_table(
        "motorbike_insurance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issued_date", sa.DATE(), nullable=False),
        sa.Column("plate_number", sa.TEXT(), nullable=False),
        sa.Column("frame_number", sa.TEXT(), nullable=True),
        sa.Column("engine_number", sa.TEXT(), nullable=True),
        sa.Column("customer_name", sa.TEXT(), nullable=True),
        sa.Column("premium_tnds", sa.REAL(), nullable=True),
        sa.Column("premium_accident", sa.REAL(), nullable=True),
        sa.Column("years", sa.Integer(), nullable=True),
        sa.Column("total_premium", sa.REAL(), nullable=True),
        sa.Column("start_date", sa.DATE(), nullable=True),
        sa.Column("end_date", sa.DATE(), nullable=True),
        sa.Column("vehicle_type", sa.TEXT(), nullable=True),
        sa.Column("brand", sa.TEXT(), nullable=True),
        sa.Column("source_email_id", sa.TEXT(), nullable=True),
        sa.Column("source_attachment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plate_number", "issued_date"),
    )
    op.create_table(
        "student_insurance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issued_date", sa.DATE(), nullable=False),
        sa.Column("insured_name", sa.TEXT(), nullable=False),
        sa.Column("insured_dob", sa.DATE(), nullable=True),
        sa.Column("insured_id_number", sa.TEXT(), nullable=True),
        sa.Column("school", sa.TEXT(), nullable=True),
        sa.Column("class_name", sa.TEXT(), nullable=True),
        sa.Column("effective_from", sa.DATE(), nullable=True),
        sa.Column("premium", sa.REAL(), nullable=True),
        sa.Column("buyer_name", sa.TEXT(), nullable=True),
        sa.Column("source_email_id", sa.TEXT(), nullable=True),
        sa.Column("source_attachment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("insured_id_number", "school", "issued_date"),
    )
    op.create_table(
        "travel_insurance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issued_date", sa.DATE(), nullable=False),
        sa.Column("insured_name", sa.TEXT(), nullable=False),
        sa.Column("insured_dob", sa.DATE(), nullable=True),
        sa.Column("insured_id_number", sa.TEXT(), nullable=True),
        sa.Column("payment_date", sa.DATE(), nullable=True),
        sa.Column("trip_start", sa.DATE(), nullable=False),
        sa.Column("trip_end", sa.DATE(), nullable=False),
        sa.Column("destination", sa.TEXT(), nullable=True),
        sa.Column("scope", sa.TEXT(), nullable=True),
        sa.Column("plan", sa.TEXT(), nullable=True),
        sa.Column("premium", sa.REAL(), nullable=True),
        sa.Column("buyer_name", sa.TEXT(), nullable=True),
        sa.Column("source_email_id", sa.TEXT(), nullable=True),
        sa.Column("source_attachment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("insured_id_number", "trip_start", "destination"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("travel_insurance")
    op.drop_table("student_insurance")
    op.drop_table("motorbike_insurance")
    op.drop_table("health_insurance")
    op.drop_table("bhyt_bhxh_insurance")
    op.drop_table("auto_insurance")
    # ### end Alembic commands ###
